### PR TITLE
Update astropy-helpers to v2.0.8

### PR DESCRIPTION
**Pull request by bsipocz**
This is an automated update of the astropy-helpers submodule to v2.0.8. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed. 

A full list of changes can be found in the [changelog](https://github.com/astropy/astropy-helpers/blob/v2.0.8/CHANGES.rst). 

*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!* 

Similarly to the core package, the v3.0+ releases of astropy-helpers require Python 3.5+. We will open automated update PRs with astropy-helpers v3.1.x only for packages that specifically opt in for it when they start supporting Python 3.5+ only. Please let @bsipocz or @astrofrog know or add your package to the list in https://github.com/astropy/astropy-procedures/blob/master/update-affiliated/helpers_3.py

### CODE REVIEW

**Comment by cdeil** [comment]
@bsipocz @astrofrog Python 2.7 on Windows fails like this!?
```
INTERNALERROR> DeprecationWarning: The `implprefix` system is deprecated please decorate this function using an instance of HookimplMarker.
```
https://ci.appveyor.com/project/Astropy/pyregion/builds/20949480/job/7woh3u1gxhe0tvkv#L521

**Comment by bsipocz** [comment]
Apparently it does 😄 

More seriously. In astroplan and stingray there are segfault like hang ups on windows and python 2.7 (neither case have been solved), but I haven't yet seen this INTERNALERROR in any other packages. I'll cross ref if see something related elsewhere.

**Comment by cdeil** [comment]
I restarted the Appveyor build and it still fails on Python 2.7 on Windows with this error:
```
INTERNALERROR> DeprecationWarning: The `implprefix` system is deprecated please decorate this function using an instance of HookimplMarker.
```

@bsipocz or @astrofrog or @mwcraig - Have you seen that before, or any idea what causes this or how to fix it?

**Comment by cdeil** [comment]
Closing this old PR. Presumably superseded by #135 .

**Pull request closed without merging**
