### PR TITLE
Update astropy-helpers to v1.3.1

### PR DESCRIPTION
**Pull request by bsipocz**
This is an automated update of the astropy-helpers submodule to v1.3.1. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.

*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*

### CODE REVIEW

**Comment by cdeil** [comment]
Fails on travis-ci:
* https://travis-ci.org/astropy/pyregion/jobs/212825159#L426
* https://travis-ci.org/astropy/pyregion/jobs/212825163#L657
(both probably unrelated to this PR)

**Comment by bsipocz** [comment]
@cdeil - There is no numpy 1.12 conda build for python 3.4. So that build should be fixed by testing with an older version. 
Regarding the docs build, I'm not sure what's going on with ``matplotlib.artist.Artist``, maybe something has changed in the API there between 1.5.x and 2.0.

**Comment by bsipocz** [comment]
Also I wonder about the status of pyregion, do we still maintain it? 

(This PR was opened automatically as it's still listed in the affiliated package register but I can remove it manually from the list of packages for helpers update if the decision is to leave it as is without further updates.)

**Comment by cdeil** [comment]
> There is no numpy 1.12 conda build for python 3.4. So that build should be fixed by testing with an older version.

Can you please just remove that build?

> Also I wonder about the status of pyregion, do we still maintain it?

As long as there is no better and complete replacement available, it would be good to maintain pyregion. And even then, there's probably several pipelines that use pyregion and will keep using it for the coming years.

In practice, the question is whether someone is willing to finish up the open PRs and put out a new release in the coming months or not.

**Comment by cdeil** [comment]
@keflavich noticed the same issues we discussed above in https://github.com/astropy/pyregion/pull/109#issuecomment-293655378 .

@bsipocz - Can you resolve this here or should I do it in a follow-up PR?
As I said above, IMO this Python 3.4 build can just be dropped from the test matrix, no need to spend time on workarounds.

**Comment by bsipocz** [comment]
Yes, it seems to be the same mpl doc build issue as over there in #109 (the py3.4 is already been solved by shuffling the np versions around). What about sticking with older mpls? or do you have a workaround idea?

**Comment by cdeil** [comment]
So the only remaining issue making travis-ci fail here is this:
```
/home/travis/build/astropy/pyregion/docs/getting_started.rst:152: WARNING: py:obj reference target not found: matplotlib.artist.Artist
```
https://travis-ci.org/astropy/pyregion/jobs/212957571#L658

Indeed `matplotlib.artist.Artist` is missing:
```
wget http://matplotlib.org/objects.inv
pip install sphobjinv
sphobjinv decode
ack Artist | grep class
```

I found https://github.com/matplotlib/matplotlib/pull/8175 , i.e. this was introduced in MPL 2.0 and will be fixed in their next release.

@bsipocz  - Could you please put double backticks here as a temp solution so that we get a passing CI build back for `pyregion`?
```
docs/getting_started.rst
154:`matplotlib.artist.Artist` objects ::
```

**Comment by bsipocz** [comment]
@cdeil - Done. I'll keep an eye on this and merge it when getting the green light from travis.

**Comment by cdeil** [comment]
@bsipocz - Thanks!

**Pull request merged**
